### ISSUE TITLE
motd glitch

### ISSUE THREAD

**Issue by xXxAaRkEtxXx** [PorkStudios/Pork2b2tBot#19]
![image](https://user-images.githubusercontent.com/38191020/57953301-5f716400-78f8-11e9-967c-10eef5b1f557.png)

**Comment by xXxAaRkEtxXx** [comment]
"motd": "§c%s" this is the motd

**Comment by VADemon** [comment]
What's the encoding of the config file? UTF-8/UTF-8 without BOM could work.

**Comment by xXxAaRkEtxXx** [comment]
how do i check?

**Comment by DaMatrix** [comment]
file encoding problem, not my fault.
